---
- name: Install PostgreSQL
  become: true
  apt:
    name:
      - postgresql
      - python-psycopg2

- name: Start Postgres
  become: true
  command: systemctl start postgresql

- become: true
  become_user: postgres
  block:
    - name: Create PostgreSQL database
      postgresql_db:
        name: "{{ database_name }}"

    - name: Create PostgreSQL users
      postgresql_user:
        name: "{{ database_user }}"
        password: "{{ database_password }}"
        db: "{{ database_name }}"
        priv: ALL

    - name: Add PostgreSQL extensions
      postgresql_ext:
        name: "{{ item }}"
        db: "{{database_name}}"
      with_items:
        - plpgsql
        - unaccent
        - pg_trgm
