---
- include_role:
    name: galaxy/geerlingguy.nginx

- name: Update Nginx template for capistrano
  become: true
  become_method: sudo
  template:
    src: "{{ playbook_dir }}/roles/capistrano/templates/consul_vhost.conf"
    dest: /etc/nginx/sites-enabled/default
    owner: "{{ deploy_user }}"
    group: wheel

- name: Restart nginx
  become: true
  service: name=nginx state=restarted
