---
- include_role:
    name: galaxy/geerlingguy.nginx

- name: Add default virtual host
  template:
    src: "{{ playbook_dir }}/roles/nginx/templates/consul_vhost.j2"
    dest: /etc/nginx/sites-enabled/default
    owner: "{{ deploy_user }}"
    group: wheel
  notify: restart nginx
