dist: xenial
language: python
python:
  - "2.7"
before_install:
  - "__rvm_unload ; rm -rf ~/.rvm"
install:
  - sudo apt-get update -y
  - sudo apt-get install -y openssh-server
  - pip install ansible
before_script:
  # Set up host inventory
  - echo "localhost ansible_connection=local" > hosts
  # Generate dummy SSH key
  - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
script: ansible-playbook app.yml -i hosts
