---
- name: Set up CONSUL
  hosts: all
  become: true
  vars:
    # https://github.com/ansible/proposals/issues/89
    ansible_user: "{{ deploy_user }}"
  roles:
    - ruby
    - rails
    - letsencrypt
    - email
    - queue
    - unicorn
    - nginx
    - memcached
    - timezone
    # - capistrano

- name: Check system
  hosts: all
  become: true
  vars:
    ansible_user: "{{ deploy_user }}"
  roles:
    - specs
