---
- name: Set up CONSUL
  hosts: all
  vars:
    # https://github.com/ansible/proposals/issues/89
    ansible_user: "{{ deploy_user }}"
  roles:
    - ruby
    - rails
    - ssl
    - email
    - queue
    - unicorn
    - role: nginx
    - memcached
    - timezone
    # - capistrano

- name: Check system
  hosts: all
  vars:
    ansible_user: "{{ deploy_user }}"
  roles:
    - specs
