---
- name: Set up CONSUL
  hosts: all
  become: true
  vars:
    # https://github.com/ansible/proposals/issues/89
    ansible_user: "{{ deploy_user }}"
  roles:
    - ruby
    - rails
    - capistrano
    - ssl
    - email
    - queue
    - unicorn
    - role: nginx
      become: true
    - memcached
    - timezone

- name: Check system
  hosts: all
  become: true
  vars:
    ansible_user: "{{ deploy_user }}"
  roles:
    - specs
