default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: {{ deploy_user}}
  password: {{ deploy_user }}

production:
  <<: *default
  database: consul_production

test:
  <<: *default
  database: consul_production
