default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: {{ deploy_user}}
  password: {{ deploy_user }}

{{ context }}:
  <<: *default
  database: consul_{{ context }}
