---
- name: Add unicorn.rb
  template:
    src: ../templates/unicorn.rb
    dest: "/home/{{ deploy_user }}/consul/config"
    owner: "{{ deploy_user }}"
    group: wheel

- name: Add unicorn files and folders
  file:
    path: "/home/{{ deploy_user}}/consul/{{ item }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: wheel
    mode: 0775
  with_items:
    - "pids" 
    - "sockets" 
    - "log"

- name: Check that Unicorn is running
  stat:
    path: "/home/{{ deploy_user }}/consul/pids/unicorn.pid"
  register: unicorn_process

- name: Get running unicorn process
  shell: "cat /home/{{ deploy_user }}/consul/pids/unicorn.pid"
  register: running_process
  when: unicorn_process.stat.exists == True

- name: Kill running process
  shell: "kill -QUIT {{ item }}"
  with_items: "{{ running_process.stdout_lines }}"
  when: unicorn_process.stat.exists == True

- name: Start Unicorn
  shell: "/home/{{ deploy_user}}/.rvm/gems/ruby-2.3.2/wrappers/unicorn -c config/unicorn.rb -E {{ env }} -D"
  args:
    chdir: /home/{{ deploy_user }}/consul
  ignore_errors: true

- name: Print unicorn errors
  shell: "cat /home/deploy/consul/log/unicorn.stderr.log"
  args:
    chdir: /home/{{ deploy_user }}/consul
    executable: /bin/bash
