---
- name: Upgrade apt packages (this may take a few minutes)
  become: true
  apt:
    upgrade: yes
    update_cache: yes
  when: not lookup('env', 'CI')

- name: Install basic packages
  become: true
  apt:
    state: latest
    update_cache: true
    name:
      - apt-transport-https
      - build-essential
      - curl
      - git-core
      - htop
      - imagemagick
      - libcurl3
      - libcurl3-gnutls
      - libcurl4-openssl-dev
      - libffi-dev
      - libpq-dev
      - libreadline-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - libyaml-dev
      - nodejs
      - ruby-dev
      - software-properties-common
      - tmux
      - vim
      - wget
      - zlib1g-dev

- name: Add Node repository
  become: true
  apt_repository:
    repo: deb https://deb.nodesource.com/node_6.x bionic main
    state: present

- name: Add Node key
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
