---
- when: domain is defined
  block:
    - name: Install software-properties-common
      apt: 
        name: software-properties-common

    - name: Add Certbot repository
      apt_repository:
        repo: "ppa:certbot/certbot"

    - name: Update system
      apt:
        update_cache: yes

    - name: Install python-certbot-nginx 
      apt:
        name: "python-certbot-nginx"

    - name: Creates letsencrypt directory
      file:
        path: /etc/letsencrypt/live
        state: directory

    - name: Grab Certbot certificate
      command: "sudo certbot --nginx --noninteractive --agree-tos --email {{ letsencrypt_email }} -d {{ domain }} --server https://acme-staging-v02.api.letsencrypt.org/directory"

    - name: Force https connection
      lineinfile:
        path: /home/{{ deploy_user }}/consul/config/environments/production.rb
        regexp: 'force_ssl'
        line: '  config.force_ssl = true'

